apiVersion: batch/v1
kind: Job
metadata:
  name: diag-network
  namespace: admin
  annotations:
    # Sync(동기화)가 발생할 때만 실행되도록 설정
    argocd.argoproj.io/hook: Sync
    # 새 job 실행전 기존의 job 삭제
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    # 관리자 서버에서 sync를 주기위한 변수값
    inspection-id: "REPLACE_THIS_VALUE"
spec:
  ttlSecondsAfterFinished: 100
  completions: 3
  parallelism: 3
  template:
    metadata:
      labels:
        job-name: diag-network
    spec:
      hostNetwork: true
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  job-name: diag-network
              topologyKey: kubernetes.io/hostname
      containers:
        - name: diag-tool
          image: suhannugul/capstonetest:latest
          args: [ "network" ]
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: job-configmap
            - secretRef:
                name: job-secret
          securityContext:
            capabilities:
              add: [ "NET_RAW" ]
      restartPolicy: Never