apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devteam-cluster-binding
subjects:
  - kind: ServiceAccount
    name: dev-team
    namespace: devteam        # SA는 devteam에 있지만 전역에 바인딩
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: devteam-cluster