apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: suhannugul/email-agent:938ba5d9ebbf2d172e8d2d71df5b38970fd594a8
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
            limits:
              memory: "1.5Gi"
          envFrom:
            - secretRef:
                name: backend-secret
            - configMapRef:
                name: backend-configmap
